#!/usr/bin/env python3
"""
Generate a precomputed dBFS envelope for a PCM WAV file and print a Kotlin PlaybackTrack snippet.
"""

from __future__ import annotations

import argparse
import base64
import math
import sys
import wave
from dataclasses import dataclass
from pathlib import Path


@dataclass
class WavInfo:
    channels: int
    sample_width: int
    sample_rate: int
    total_frames: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate precomputed playback envelope for Kotlin.")
    parser.add_argument("--wav", required=True, help="Path to PCM .wav file")
    parser.add_argument("--track-id", required=True, help='Track id, e.g. "rain_from_indoors"')
    parser.add_argument("--title", required=True, help='Track title, e.g. "Rain From Indoors"')
    parser.add_argument("--raw-res-id", required=True, help='Raw resource symbol name, e.g. "rain_from_indoors_perfect_loop"')
    parser.add_argument("--hop-ms", type=int, default=10, help="Envelope hop size in milliseconds")
    parser.add_argument("--db-floor", type=float, default=-80.0, help="Minimum dBFS encoded in the envelope")
    parser.add_argument("--db-ceiling", type=float, default=0.0, help="Maximum dBFS encoded in the envelope")
    return parser.parse_args()


def decode_sample(sample_bytes: bytes, sample_width: int) -> int:
    if sample_width == 1:
        # 8-bit PCM WAV is unsigned.
        return sample_bytes[0] - 128
    return int.from_bytes(sample_bytes, byteorder="little", signed=True)


def scan_wav(path: Path) -> WavInfo:
    with wave.open(str(path), "rb") as wav:
        return WavInfo(
            channels=wav.getnchannels(),
            sample_width=wav.getsampwidth(),
            sample_rate=wav.getframerate(),
            total_frames=wav.getnframes(),
        )


def compute_linear_rms_levels(path: Path, hop_ms: int) -> tuple[list[float], WavInfo]:
    info = scan_wav(path)
    if info.sample_width not in (1, 2, 3, 4):
        raise ValueError(f"Unsupported sample width: {info.sample_width} bytes")

    hop_frames = max(1, int(info.sample_rate * (hop_ms / 1000.0)))
    frame_size = info.channels * info.sample_width
    max_abs = float((1 << (8 * info.sample_width - 1)) - 1)

    levels: list[float] = []

    with wave.open(str(path), "rb") as wav:
        while True:
            data = wav.readframes(hop_frames)
            if not data:
                break

            frames = len(data) // frame_size
            if frames <= 0:
                break

            sum_sq = 0.0
            for i in range(frames):
                offset = i * frame_size
                mono = 0.0
                for ch in range(info.channels):
                    start = offset + ch * info.sample_width
                    end = start + info.sample_width
                    mono += decode_sample(data[start:end], info.sample_width)
                mono /= info.channels
                sum_sq += mono * mono

            rms = math.sqrt(sum_sq / frames) / max_abs
            levels.append(rms)

    return (levels or [0.0]), info


def linear_to_dbfs(linear: float, db_floor: float) -> float:
    if linear <= 1e-12:
        return db_floor
    return max(db_floor, min(0.0, 20.0 * math.log10(linear)))


def encode_dbfs_levels_base64(levels: list[float], db_floor: float, db_ceiling: float) -> str:
    if db_ceiling <= db_floor:
        raise ValueError("--db-ceiling must be greater than --db-floor")
    span = db_ceiling - db_floor
    quantized = bytes(
        int(
            max(
                0,
                min(
                    255,
                    round(((linear_to_dbfs(level, db_floor) - db_floor) / span) * 255.0),
                ),
            )
        )
        for level in levels
    )
    return base64.b64encode(quantized).decode("ascii")


def emit_kotlin(args: argparse.Namespace, levels_b64: str, info: WavInfo, bin_count: int) -> str:
    duration_sec = info.total_frames / info.sample_rate if info.sample_rate > 0 else 0.0
    return f"""// Generated by scripts/generate_playback_envelope.py
// Source: {args.wav}
// PCM: {info.channels}ch, {info.sample_width * 8}-bit, {info.sample_rate}Hz, {duration_sec:.3f}s
// hopMs={args.hop_ms}, bins={bin_count}, dbFloor={args.db_floor}, dbCeiling={args.db_ceiling}
PlaybackTrack(
    id = "{args.track_id}",
    title = "{args.title}",
    rawResId = R.raw.{args.raw_res_id},
    envelopeHopMs = {args.hop_ms},
    envelopeDbfsLevels = decodeDbfsLevels("{levels_b64}")
)"""


def main() -> int:
    args = parse_args()
    if args.hop_ms <= 0:
        print("ERROR: --hop-ms must be > 0", file=sys.stderr)
        return 1
    if args.db_ceiling <= args.db_floor:
        print("ERROR: --db-ceiling must be greater than --db-floor", file=sys.stderr)
        return 1

    wav_path = Path(args.wav)
    if not wav_path.exists():
        print(f"ERROR: File not found: {wav_path}", file=sys.stderr)
        return 1

    try:
        levels, info = compute_linear_rms_levels(wav_path, args.hop_ms)
        levels_b64 = encode_dbfs_levels_base64(levels, args.db_floor, args.db_ceiling)
    except (wave.Error, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(emit_kotlin(args, levels_b64, info, len(levels)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
